services:
  - type: web
    name: newsphere-dashboard
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      # Set these in Render Dashboard -> Environment
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      # Optional: If you want to override auto-detected callback base URL
      # - key: BASE_URL
      #   value: https://your-service.onrender.com